# -*- coding: utf-8 -*-
"""figseries — "swap two figures to fix the sequence", correct by construction.

MODELLED ON: vdo-vpdo 2023-07-09 Q22 — see the real figure at
corpus/reasoning-reference/vdo-vpdo-2023-07-09/page5.png. Five squares in a
strip, each divided by BOTH diagonals into four triangular quadrants (top,
left, right, bottom), each quadrant holding one of four symbols. The first
square is unnumbered; the rest are numbered 1..4. Exactly one swap of two
numbered figures restores the series, and the answer is the number of the
EARLIER of the two.

VERIFIED before building: the real strip's symbols are one set of four rotating
around the quadrants a fixed step per figure. Reading the clean (unwatermarked)
Hindi column at 3x, the base square is (top,left,right,bottom) = ○ □ △ + and
printed figures 1 and 2 are precisely the 2nd and 1st members of the
anticlockwise series — i.e. they are each other's swap, so the earlier of the
two is 1, which is the real paper's keyed answer (A).

HOW IT IS CORRECT BY CONSTRUCTION: the true series is GENERATED by rotating a
symbol tuple, then two positions are swapped. The answer is the index of the
first swapped position — known because we performed the swap, never inferred
from the picture. The picture is drawn from the same tuples, so the strip and
the key cannot disagree.

WHY THE ANSWER CANNOT BE AMBIGUOUS: a swap is only emitted if it is the UNIQUE
pair whose exchange restores the series (checked exhaustively over all 6 pairs
before returning). A rotation of period 4 over 4 shown figures can otherwise
admit a second valid swap, which would make two options correct.

Interface:
    generate(rng)                  -> question dict (with `_figure`)
    series(start, step, n)         -> list[tuple]   # pure, for tests
    restoring_swaps(shown, truth)  -> list[tuple]   # pure, for tests
"""
from __future__ import annotations

import random
from itertools import combinations

# The four symbols, as figure-spec tokens. figures.py maps these to drawings —
# they are NOT text glyphs, because the container has no guaranteed Latin or
# symbol font (see figures.py's font chain).
SYMBOLS = ("circle", "square", "triangle", "plus")

# Quadrant order used everywhere in this module: (top, left, right, bottom).
QUADRANTS = ("top", "left", "right", "bottom")


def rotate(quad: tuple, clockwise: bool = True) -> tuple:
    """One rotation step of the four symbols around the quadrants. O(1).

    Clockwise means top->right->bottom->left->top, which for a tuple ordered
    (top, left, right, bottom) is the reindexing below. Written out rather than
    done with a rotated list because the tuple order is NOT the cycle order —
    that mismatch is exactly where an off-by-one hides.
    """
    t, l, r, b = quad
    if clockwise:
        # left->top, bottom->left, top->right, right->bottom
        return (l, b, t, r)
    # right->top, top->left, bottom->right, left->bottom
    return (r, t, b, l)


def series(start: tuple, clockwise: bool, n: int) -> list[tuple]:
    """The true n-figure series beginning at `start`. O(n)."""
    out = [start]
    for _ in range(n - 1):
        out.append(rotate(out[-1], clockwise))
    return out


def restoring_swaps(shown: list[tuple], truth: list[tuple]) -> list[tuple]:
    """Every (i, j) whose exchange turns `shown` into `truth`. O(n^2 * n).

    n is 4, so this is 6 pairs x a 4-element compare — trivial. Exhaustive by
    design: the question is only well-posed if exactly ONE pair works, and the
    only way to know that is to try them all.
    """
    found = []
    for i, j in combinations(range(len(shown)), 2):
        cand = list(shown)
        cand[i], cand[j] = cand[j], cand[i]
        if cand == truth:
            found.append((i, j))
    return found


_STEM = (
    "नीचे दिये गये प्रश्न में पाँच आकृतियाँ हैं । आकृतियों से बनी शृंखला पहली "
    "आकृति से प्रारम्भ होती है, जिस पर कोई अंक अंकित नहीं है, तथा अन्य आकृतियों "
    "पर क्रम से 1 से 4 अंक अंकित हैं । यदि यह शृंखला तभी स्थापित होगी यदि किन्हीं "
    "दो अंकित आकृतियों को परस्पर बदल दिया जाये । इन दोनों आकृतियों में से पहले "
    "आयी हुई आकृति पर अंकित अंक ही उत्तर है ।"
)


def generate(rng: random.Random) -> dict:
    """One figure-series question. O(1) — the retry loop is bounded below.

    Builds the true 5-figure series, swaps two of the four NUMBERED figures,
    and keys the earlier one. Rejects any swap that is not uniquely restoring,
    which would make more than one option defensible.
    """
    # Bounded retry: with 4 shown figures and a period-4 rotation, some swaps
    # are ambiguous (two different pairs both restore the series). 6 pairs are
    # tried per attempt, so this terminates quickly; the cap only guards
    # against a future rule change making every swap ambiguous.
    for _ in range(40):
        start = list(SYMBOLS)
        rng.shuffle(start)
        start = tuple(start)
        clockwise = rng.choice((True, False))

        truth = series(start, clockwise, 5)
        numbered = truth[1:]                      # figures 1..4

        i, j = sorted(rng.sample(range(4), 2))
        shown = list(numbered)
        shown[i], shown[j] = shown[j], shown[i]

        # The candidate must be fixable by exactly ONE swap — ours.
        swaps = restoring_swaps(shown, numbered)
        if swaps != [(i, j)]:
            continue

        answer_num = i + 1                        # the EARLIER of the two
        return {
            "stem": _STEM + " सही विकल्प का चयन करें :",
            "options": ["1", "2", "3", "4"],
            "answer": "abcd"[answer_num - 1],
            "format": "plain",
            # Intrinsic: a swap involving the first figure is spotted as soon
            # as the candidate checks figure 1 against the base; a swap deeper
            # in the strip needs the rule to be held across more figures.
            "difficulty": "moderate" if i == 0 else "hard",
            "reason": (
                f"शृंखला में प्रत्येक आकृति में चारों चिह्न एक स्थान "
                f"{'दक्षिणावर्त' if clockwise else 'वामावर्त'} घूमते हैं । "
                f"आकृति {i + 1} व {j + 1} को परस्पर बदलने पर क्रम स्थापित हो "
                f"जाता है; अतः पहले आयी आकृति का अंक {answer_num} उत्तर है ।"
            ),
            "_type": "figseries",
            "_dedup_key": f"figseries:{start}:{clockwise}:{i}{j}",
            "_figure": {
                "kind": "figseries",
                # The base square first, then the four numbered ones AS SHOWN
                # (i.e. already swapped) — the renderer draws exactly this.
                "squares": [list(truth[0])] + [list(q) for q in shown],
                "labels": ["", "1", "2", "3", "4"],
            },
        }

    raise RuntimeError("figseries: no uniquely-restoring swap found in 40 tries")
